# example netlify.toml
[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

## Uncomment to use this redirect for Single Page Applications
## Not needed for static site generators.
[[redirects]]
  /api/* https://165.227.220.80/:3000 200
  /* /index.html 200  
  from = "/*"
  to = "/index.html"
  status = 200