# example netlify.toml
[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

## Uncomment to use this redirect for Single Page Applications
## Not needed for static site generators.


[[redirects]]
  from = "/api/*"
  to = "https://api.cucked.soy/:splat"
  force = true
  status = 200