# example netlify.toml
[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

## Uncomment to use this redirect for Single Page Applications
## Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://api.cucked.soy:3002"
  force = true
  status = 200

  [[redirects]]
  from = "/ip"
  to = "https://api.ipify.org/?format=json"
  force = true
  status = 200